image: ruby2.2.0
script:
  - mkdir -p /tmp/bundler
  - sudo chown ubuntu:ubuntu /tmp/bundler
  - bundle install --path=/tmp/bundler --deployment --quiet
  - bundle exec rake test
services:
  - postgres
env:
  - PG_USER=postgresql
  - PG_PASSWORD=""
  - PG_HOSTNAME=localhost
  - RAILS_ENV=test
cache:
  - /tmp/bundler
notify:
  email:
    recipients:
