image: ruby2.0.0
script:
  - mkdir -p /tmp/bundler
  - sudo chown ubuntu:ubuntu /tmp/bundler
  - bundle install --path=/tmp/bundler --deployment
  - psql -c 'drop database boxed_;create database boxed_;' -U postgres -h 127.0.0.1
  - bundle exec rake test
services:
  - postgres
env:
  - PG_USER=postgres
  - PG_PASSWORD=""
  - PG_HOSTNAME=localhost
  - RAILS_ENV=test
cache:
  - /tmp/bundler
notify:
  email:
    recipients:
