image: bradrydzewski/ruby:2.1.1
script:
  - mkdir -p /tmp/bundler
  - sudo chown ubuntu:ubuntu /tmp/bundler
  - bundle install --path=/tmp/bundler --deployment --quiet
  - bundle exec rake test
services:
cache:
  - /tmp/bundler
notify:
  email:
    recipients:
