image: ruby2.0.0
script:
  - mkdir -p /tmp/bundler
  - sudo chown ubuntu:ubuntu /tmp/bundler
  - bundle install --path=/tmp/bundler --deployment
  - su - postgre -c 'dropdb boxed_'
  - su - postgre -c 'createdb boxed_'
  - bundle exec rake test
services:
  - postgres
env:
  - PG_USER=postgres
  - PG_PASSWORD=""
  - PG_HOSTNAME=localhost
  - RAILS_ENV=test
cache:
  - /tmp/bundler
notify:
  email:
    recipients:
