development:
  adapter: postgresql
  encoding: unicode
  database: boxed_dev<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD']  %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: 5432
  
  
test:
  adapter: postgresql
  encoding: unicode
  database: boxed_<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] || 'localhost' %>
  port: 5432


production:
  adapter: postgresql
  encoding: unicode
  database: boxed_production
  pool: 5
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>
  port: 5432
